### ISSUE TITLE
Missing one dependency for Kubuntu; maybe you forgot to put it on readme?

### ISSUE THREAD

**Issue by sevenzerotwo** [Alban-Boissard/kwin-effects-blur-respect-rounded-decorations#1]
Hi! Thank you for your amazing work in fixing the "korners" blur bug, it works flawlessly in my Kubuntu 21.10. But, seems like you forgot something to put on readme, there's one dependency that need to download in Kubuntu.

It's libkwaylandserver-dev.

Before i installed it, the source refuses to build because of that dependency. I downloaded it and rebuilding it again, turned out works. I forgot to take a screenshot of it due when rebuilding the past terminal outputs are cleared. Maybe you could update the readme to prevent others having same issues as i am. Thank you!

**Comment by Alban-Boissard** [comment]
Thanks for reporting !
I added the missing dependency on readme.
