### ISSUE TITLE
Build error on Manjaro KDE Plasma v5.24.3

### ISSUE THREAD

**Issue by tnilzon** [Alban-Boissard/kwin-effects-blur-respect-rounded-decorations#13]
Please fix, thanks!

Output
------
/home/tomas/Downloads/kwin-effects-blur-respect-rounded-decorations-master/src/plugin.cpp:12: Parse error at "FILE"

make[2]: *** [src/CMakeFiles/kwin4_effect_blur2_autogen.dir/build.make:71: src/CMakeFiles/kwin4_effect_blur2_autogen] Error 1
make[1]: *** [CMakeFiles/Makefile2:440: src/CMakeFiles/kwin4_effect_blur2_autogen.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by Naxdy** [comment]
Have a look at pull request #10 

This repo seems to be unmaintained, but I could successfully build using that commit.

**Comment by tnilzon** [comment]
Does not work for me:
>Output
>------
>/home/tomas/Downloads/kwin-effects-blur-respect-rounded-decorations-master/src/plugin.cpp:12: Parse error at "FILE"
make[2]: *** [src/CMakeFiles/kwin4_effect_blur2_autogen.dir/build.make:71: src/CMakeFiles/kwin4_effect_blur2_autogen] Error 1
make[1]: *** [CMakeFiles/Makefile2:440: src/CMakeFiles/kwin4_effect_blur2_autogen.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

My system:
Operating System: Manjaro Linux
KDE Plasma Version: 5.24.3
KDE Frameworks Version: 5.91.0
Qt Version: 5.15.3
Kernel Version: 5.16.14-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-9700K CPU @ 3.60GHz
Memory: 31,2 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 630

**Comment by tnilzon** [comment]
[UPDATE]: My mistake, it works!
/sorry...

**Comment by Alban-Boissard** [comment]
I just merge the patchs form  zzag and aleasto.
It works for me.
