### ISSUE TITLE
Bottom corners clip squares while using LightlyShaders

### ISSUE THREAD

**Issue by naraklog** [Alban-Boissard/kwin-effects-blur-respect-rounded-decorations#3]
While using Lightlyshaders (or ShapeCorners) here is a look at the bottom corner (extreme radius) 
![image](https://user-images.githubusercontent.com/30985448/144816646-041bb448-5be1-481e-aa69-87babe2d5927.png)

And here is how top corners are handled at the same radius
![image](https://user-images.githubusercontent.com/30985448/144816815-1681d913-ccf7-4de2-a51e-658615acadef.png)

This causes the blur to clip into the window and shows transparent areas.
I feel this is happening because we have to disable the window borders of the Decorations for LightlyShaders to take affect.

**Comment by naraklog** [comment]
Also is it possible that you could patch the Force Blur KWin Script to use this effect instead of the regular Blur effect? Because when force blur is used the Korners bug persists

**Comment by Alban-Boissard** [comment]
I can reproduce the issue. The way lightlyShaders handles the corners is not compatible with the way this effect works.  
You maybe can try 
https://github.com/a-parhom/LightlyShaders
that handle the corners bug itself.

**Comment by Alban-Boissard** [comment]
A close the issue, and update the readme to inform of the incompatibility with LightlyShaders.

**Comment by naraklog** [comment]
But isn't it possible to round the bottom corners the same way as you rounded the top?
