### ISSUE TITLE
Unable to build on Neon User Edition

### ISSUE THREAD

**Issue by begonia208** [Alban-Boissard/kwin-effects-blur-respect-rounded-decorations#5]
Your solution to the "corner bug" looked very promising. But I regret to say that it won't build in Neon User edition. I am not at all a programmer but perhaps the file I attached could give you useful  information. Your screenshot looks fantastic! 
[CMakeOutput.log](https://github.com/Alban-Boissard/kwin-effects-blur-respect-rounded-decorations/files/7682609/CMakeOutput.log)

**Comment by GolDNenex** [comment]
Im also on KDE neon, installing  "libwayland-dev" fix the problem for me.
![image](https://user-images.githubusercontent.com/30295660/145487494-bb9b54f0-9636-40d0-aa52-0ff0071cf3a5.png)
![image](https://user-images.githubusercontent.com/30295660/145487585-87521586-71cf-4b40-a43b-4668235ea6ee.png)

**Comment by begonia208** [comment]
Thank you very much for your tip! It worked, also on my machine. The kwin-effect installed totally as it should.
The new blur-effect appears in my system-settings too. 
But what ever I try with the sliders, I won't get those beautiful rounded corners!

**Comment by Alban-Boissard** [comment]
Do you have disable the normal blur effect ? 

(I added the missing dep in the readme, thanks for reporting and thanks to GolDNenex to find the missing one.

**Comment by begonia208** [comment]
I checked... Yes, I have disabled the normal blur effect. 
I checked if any other rounded corner tweak left-over is in the way, but I couldn't find any.
But the new blur effect of your  kwin-effects-blur-respect-rounded-decorations works like a charm!

**Comment by begonia208** [comment]
Does kwin-effects-blur-respect-rounded-decorations produce a configuration file in the folder ~/.config? How is it called?

**Comment by begonia208** [comment]
Sorry, I see it now. It's in the file kwinrc. I find there:
```
[Effect-Blur-Respect-Rounded-Corners]
BottomDecorationRadius=30
TopDecorationRadius=0
```
But I have no rounded corners.

**Comment by Alban-Boissard** [comment]
Not that the effect doen't round the corners. It just removes blur from the corner if your deco provide rounded corners.
What is your window decorations ?
You can try "Clisskstyle" (see the readme) for a decoration with rounded corners.

**Comment by begonia208** [comment]
I use the fantastic Lightly (I have to build it myself) theme. But I built the "classikstyles" theme from source, from github, and that too doesn't work with me. 
So I understand that your tweak only gets rid of the rounded corner bug. But what program do you use to make the corners round? The ones I tried a) do not work anymore or b) apparently are not compatible with kwin-effects-blur-respect-rounded-decorations...

**Comment by Alban-Boissard** [comment]
I use "classikstyle" and it work well for me. You can choose the radius of the Corners in the settings. If you want **bottom** rounded corners, you have to set the bordersize of the decoration to anything but no border,   depending of the radius you use.

**Comment by Alban-Boissard** [comment]
I close this issue, tanks to GolDNenex.
