### ISSUE TITLE
Any chance to see this project merge with the default blur effect?

### ISSUE THREAD

**Issue by TacoCake** [Alban-Boissard/kwin-effects-blur-respect-rounded-decorations#7]
As per the title, 
is there any chance to apply the patches from this fork to the original project, so users don't need to install a third party effect just to fix this bug?

Thanks!

**Comment by PercyDLR** [comment]
From what I know the kde team is thinking from another solution involved with masking for aurorae themes (as with the included plasma themes). With this, the corner-bug fixing would depend on whether the developers of each theme.

You could check this thread to follow the development of this solution (is not merged yet):
https://bugs.kde.org/show_bug.cgi?id=395725

**Comment by Alban-Boissard** [comment]
Hello,
The bug seems to be solved upstream in plasma 5.25 (https://invent.kde.org/plasma/kwin/-/commit/bcff044c738891aa7e55b67cf6b21f94319eead4)
