### ISSUE TITLE
Bottom corners have a reverse korner bug

### ISSUE THREAD

**Issue by flyingmonkey01** [Alban-Boissard/kwin-effects-blur-respect-rounded-decorations#9]
Even though I have set bottom corner radius to zero, there's a weird artifact in the bottom corners of blurred windows.
plasmashell version 5.23.5
![dolphin](https://user-images.githubusercontent.com/74193215/149289746-abd7b864-d84b-4c9a-9ffc-0de4ac8a0311.png)
![terminal](https://user-images.githubusercontent.com/74193215/149289763-09d27413-af2a-4394-93b9-c96a1eda90eb.png)
A person from reddit has reported the same thing but the bug didn't disappear after multiple reboots. Also "no borders" option for maximized windows doesn't seem to effect the issue (I tried turning it off and reverse korners were still there).

**Comment by rmburg** [comment]
I experience something very similar, where the bottom corners are transparent, but not blurred. The size of the non-blurred square changes with the "bottom corner radius" setting.
![image](https://user-images.githubusercontent.com/42248344/150636848-769a1bd7-0579-4254-b27b-1b7d29ed983c.png)
Edit: When the bottom corner radius is set to zero, it looks just like @flyingmonkey01's image.

**Comment by p0ryae** [comment]
Yes! I have the same problem, but only on bottom left corner and its only present when the window is on top of another window.

I'm using pr 10 for compatibility fixes

**Comment by rmburg** [comment]
A fix for the korner bug was just merged.
https://invent.kde.org/plasma/kwin/-/merge_requests/1961

**Comment by Alban-Boissard** [comment]
Thanks for this link.
A close the issue.
